/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE courseBaseService PLEASE EDIT ../course.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Course } from '../../domain/schoolmg_db/course';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../course.service.ts
 */

/*
 * SCHEMA DB course
 *
	{
		name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_course: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		_teacher: [{
			type: Schema.ObjectId,
			ref : "teacher"
		}],
		course: [{
			type: Schema.ObjectId,
			ref : "student"
		}],
	}
 *
 */
@Injectable()
export class CourseBaseService {

    private courseCollection: AngularFirestoreCollection<Course>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.courseCollection = afs.collection<Course>('course');
    }


    // CRUD METHODS

    /**
    * courseService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Course): Promise<DocumentReference> {
        return this.courseCollection.add(item);
    }

    /**
    * courseService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.courseCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * courseService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): AngularFirestoreDocument<Course> {
        return this.afs.doc<Course>('course/' + id);
    }

    /**
    * courseService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Course[]> {
        return this.afs.collection('course').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Course;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * courseService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Course>, item: Course): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
