/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE examBaseService PLEASE EDIT ../exam.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Exam } from '../../domain/schoolmg_db/exam';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../exam.service.ts
 */

/*
 * SCHEMA DB exam
 *
	{
		place: {
			type: 'String'
		},
		score: {
			type: 'Number'
		},
		validate: {
			type: 'Boolean'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_course: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		_student: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		_teacher: {
			type: Schema.ObjectId,
			ref : "exam"
		},
	}
 *
 */
@Injectable()
export class ExamBaseService {

    private examCollection: AngularFirestoreCollection<Exam>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.examCollection = afs.collection<Exam>('exam');
    }


    // CRUD METHODS

    /**
    * examService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Exam): Promise<DocumentReference> {
        return this.examCollection.add(item);
    }

    /**
    * examService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.examCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * examService.findBy_course
    *   @description CRUD ACTION findBy_course
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_course(id: string): Observable<any[]> {
        return this.afs.collection('exam', ref => ref.where('_course', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Exam;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * examService.findBy_student
    *   @description CRUD ACTION findBy_student
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_student(id: string): Observable<any[]> {
        return this.afs.collection('exam', ref => ref.where('_student', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Exam;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * examService.findBy_teacher
    *   @description CRUD ACTION findBy_teacher
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_teacher(id: string): Observable<any[]> {
        return this.afs.collection('exam', ref => ref.where('_teacher', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Exam;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * examService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): AngularFirestoreDocument<Exam> {
        return this.afs.doc<Exam>('exam/' + id);
    }

    /**
    * examService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Exam[]> {
        return this.afs.collection('exam').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Exam;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * examService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Exam>, item: Exam): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs


    /**
    * examService.validate
    *   @description This Api is used to validate the exam
    *   @param String id id of thexam
    *   @returns Boolean
    *
    */
    validate(...params: any[]): Observable<any> {
        const callable = this.fns.httpsCallable('validate');
        return callable(params);
    }

}
