/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE studentBaseService PLEASE EDIT ../student.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Student } from '../../domain/schoolmg_db/student';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../student.service.ts
 */

/*
 * SCHEMA DB student
 *
	{
		dob: {
			type: 'Date'
		},
		name: {
			type: 'String',
			required : true
		},
		surname: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_student: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		course: [{
			type: Schema.ObjectId,
			ref : "student"
		}],
	}
 *
 */
@Injectable()
export class StudentBaseService {

    private studentCollection: AngularFirestoreCollection<Student>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.studentCollection = afs.collection<Student>('student');
    }


    // CRUD METHODS

    /**
    * studentService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Student): Promise<DocumentReference> {
        return this.studentCollection.add(item);
    }

    /**
    * studentService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.studentCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * studentService.findBycourse
    *   @description CRUD ACTION findBycourse
    *   @param Objectid key Id of model to search for
    *
    */
    findByCourse(id: string): Observable<any[]> {
        return this.afs.collection('student', ref => ref.where('course', 'array-contains', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Student;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * studentService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): AngularFirestoreDocument<Student> {
        return this.afs.doc<Student>('student/' + id);
    }

    /**
    * studentService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Student[]> {
        return this.afs.collection('student').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Student;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * studentService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Student>, item: Student): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
