/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE teacherBaseService PLEASE EDIT ../teacher.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Teacher } from '../../domain/schoolmg_db/teacher';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../teacher.service.ts
 */

/*
 * SCHEMA DB teacher
 *
	{
		name: {
			type: 'String'
		},
		surname: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_teacher: {
			type: Schema.ObjectId,
			ref : "exam"
		},
		_teacher: [{
			type: Schema.ObjectId,
			ref : "teacher"
		}],
	}
 *
 */
@Injectable()
export class TeacherBaseService {

    private teacherCollection: AngularFirestoreCollection<Teacher>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.teacherCollection = afs.collection<Teacher>('teacher');
    }


    // CRUD METHODS

    /**
    * teacherService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Teacher): Promise<DocumentReference> {
        return this.teacherCollection.add(item);
    }

    /**
    * teacherService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.teacherCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * teacherService.findBy_teacher
    *   @description CRUD ACTION findBy_teacher
    *   @param Objectid key Id of model to search for
    *
    */
    findBy_teacher(id: string): Observable<any[]> {
        return this.afs.collection('teacher', ref => ref.where('_teacher', 'array-contains', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Teacher;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * teacherService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): AngularFirestoreDocument<Teacher> {
        return this.afs.doc<Teacher>('teacher/' + id);
    }

    /**
    * teacherService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Teacher[]> {
        return this.afs.collection('teacher').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Teacher;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * teacherService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Teacher>, item: Teacher): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
